# src/ai_agent/claims_agent.py
"""Claims Agent – Gemini RAG wrapper.

Provides a simple class `ClaimsAgent` that:
- Loads the synthetic dataset (CSV) into a pandas DataFrame.
- Builds a basic in‑memory retriever using sentence‑transformers embeddings for the
  `descripcion` field (the free‑text claim narrative).
- Sends a prompt to Gemini (1.5 Flash) that includes the retrieved most similar
  claims and the user question, and returns the model's response.

The agent is deliberately lightweight because the heavy training (Isolation Forest /
XGBoost) lives in `src/models/fraud_model.py`.  Here we only need a retrieval step
and a call to the Gemini API, which the user will execute in a Colab notebook
or locally.

Dependencies (declared in `requirements.txt`):
- google-generativeai
- sentence-transformers
- pandas
- numpy
"""

import os
import pandas as pd
import numpy as np
from pathlib import Path
from typing import List

import google.generativeai as genai
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity


class ClaimsAgent:
    """Simple Retrieval‑Augmented Generation (RAG) for claim queries.

    Parameters
    ----------
    data_path: str or Path
        Path to the CSV file containing the synthetic claims (generated by
        `scripts/generate_synthetic.py`).
    embed_model_name: str, optional
        Name of the sentence‑transformers model used for embedding claim
        narratives. Default is a lightweight multilingual model.
    top_k: int, optional
        Number of most similar claims to retrieve for the prompt.
    """

    def __init__(
        self,
        data_path: str | Path = "data/raw/siniestros.csv",
        embed_model_name: str = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
        top_k: int = 5,
    ) -> None:
        self.data_path = Path(data_path)
        if not self.data_path.is_file():
            raise FileNotFoundError(f"Dataset not found at {self.data_path}")
        self.df = pd.read_csv(self.data_path)
        # Ensure the description column exists (generated by the synthetic script)
        if "descripcion" not in self.df.columns:
            raise ValueError("Column 'descripcion' missing from dataset")

        self.top_k = top_k
        # Load embedding model once (takes a few seconds)
        self.embedder = SentenceTransformer(embed_model_name)
        # Pre‑compute embeddings for all narratives for fast retrieval
        self._prepare_embeddings()

        # Initialise Gemini client – the API key is read from the environment
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key:
            raise EnvironmentError(
                "GEMINI_API_KEY not set in environment. Please copy .env.example and set it."
            )
        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel("gemini-1.5-flash")

    def _prepare_embeddings(self) -> None:
        """Compute and store embeddings for the claim narratives.

        The embeddings are stored in ``self.embeddings`` as a NumPy array of shape
        (n_claims, embedding_dim).  ``self.descriptions`` keeps the raw text for
        later lookup.
        """
        self.descriptions: List[str] = self.df["descripcion"].astype(str).tolist()
        self.embeddings = self.embedder.encode(self.descriptions, show_progress_bar=False)
        # Normalise for cosine similarity (makes later computation faster)
        self.embeddings = self.embeddings / np.linalg.norm(self.embeddings, axis=1, keepdims=True)

    def _retrieve_similar(self, query: str) -> pd.DataFrame:
        """Return the *top_k* most similar claim rows for the given query.

        The similarity is based on cosine distance between the query embedding
        and the pre‑computed claim embeddings.
        """
        query_emb = self.embedder.encode([query])
        query_emb = query_emb / np.linalg.norm(query_emb)
        sims = cosine_similarity(query_emb, self.embeddings).flatten()
        top_idx = np.argsort(sims)[-self.top_k :][::-1]
        return self.df.iloc[top_idx]

    def answer_question(self, question: str) -> str:
        """Answer a natural‑language question about the claims.

        The method builds a prompt that contains:
        1. A short system instruction describing the assistant's role.
        2. The *top_k* most similar claim records (as a markdown table).
        3. The user question.
        Gemini then generates a response that can reference the retrieved rows.
        """
        similar_df = self._retrieve_similar(question)
        # Convert to markdown for the model – keep only a few columns for brevity
        table_md = similar_df["id_siniestro descripcion riesgo".split()].to_markdown(index=False)
        prompt = (
            "You are an AI assistant for insurance fraud analysts. "
            "Use the provided table of the most similar claim records to answer the question. "
            "If the answer requires a numeric value or a list, be explicit. "
            f"\n\nSimilar claims (top {self.top_k}):\n{table_md}\n\nQuestion: {question}\n\nAnswer:"
        )
        response = self.model.generate_content(prompt)
        return response.text


# Example usage (will be run in Colab or a script, not during import)
if __name__ == "__main__":
    agent = ClaimsAgent()
    q = "What providers are associated with the highest number of red alerts?"
    print(agent.answer_question(q))
