"""src/app/main.py
Streamlit application entry point for the fraud detection prototype.
Features (as requested):
- Tailwind CSS via CDN for a clean Notion‑like look
- KPI cards (dynamic percentages, counts)
- Interactive table of incidents (color‑coded semáforo)
- PyVis network graph visualising relationships between
  asegurados, proveedores and siniestros.
- Simple navigation sidebar for future expansion.

The script is deliberately lightweight – heavy data processing lives
in the `src` package (feature engineering, model, explainability, …).
The UI loads the synthetic CSV generated by `scripts/generate_synthetic.py`
which is expected under ``data/processed/siniestros.csv``.
"""

import os
from pathlib import Path
import pandas as pd
import streamlit as st
from pyvis.network import Network
import base64

# ---------------------------------------------------------------------
# Helper utilities
# ---------------------------------------------------------------------

def load_data() -> pd.DataFrame:
    """Load the processed siniestros CSV.
    Returns an empty DataFrame with a warning if the file is missing.
    """
    data_path = Path(__file__).parents[3] / "data" / "processed" / "siniestros.csv"
    if not data_path.is_file():
        st.warning(
            f"Dataset not found at **{data_path}**. Run the synthetic data generator first."
        )
        return pd.DataFrame()
    df = pd.read_csv(data_path, parse_dates=["fecha_ocurrencia", "fecha_reporte"])
    return df

def compute_kpis(df: pd.DataFrame) -> dict:
    """Calculate the KPI values used in the dashboard.
    The function expects the column ``score`` (0‑100) and ``color``
    (verde/amarillo/rojo) already generated by the model pipeline.
    """
    total = len(df)
    if total == 0:
        return {}
    kpi = {
        "total_cases": total,
        "green_pct": round((df["color"] == "verde").mean() * 100,  # type: ignore
        "yellow_pct": round((df["color"] == "amarillo").mean() * 100,  # type: ignore
        "red_pct": round((df["color"] == "rojo").mean() * 100,  # type: ignore
        "top_risk": df.nlargest(10, "score")[["id_siniestro", "score", "color"]].to_dict(orient="records"),
    }
    return kpi

def render_kpis(kpi: dict):
    """Render KPI cards using Tailwind‑style HTML.
    ``st.markdown`` with ``unsafe_allow_html=True`` is used because
    Streamlit does not yet support Tailwind classes natively.
    """
    if not kpi:
        return
    # Simple three‑column layout
    col1, col2, col3 = st.columns(3)
    card_template = """
    <div class="p-4 rounded-lg shadow bg-white dark:bg-gray-800 text-center">
        <h3 class="text-lg font-medium text-gray-700 dark:text-gray-200">{title}</h3>
        <p class="text-2xl font-semibold text-indigo-600 dark:text-indigo-400">{value}%</p>
    </div>
    """
    with col1:
        st.markdown(
            card_template.format(title="Verde", value=kpi["green_pct"]),
            unsafe_allow_html=True,
        )
    with col2:
        st.markdown(
            card_template.format(title="Amarillo", value=kpi["yellow_pct"]),
            unsafe_allow_html=True,
        )
    with col3:
        st.markdown(
            card_template.format(title="Rojo", value=kpi["red_pct"]),
            unsafe_allow_html=True,
        )

def render_table(df: pd.DataFrame):
    """Display the incidents table with colour‑coded rows.
    Streamlit's ``st.dataframe`` is used for simplicity; the colour is
    shown in a dedicated column.
    """
    if df.empty:
        return
    # Add a column with a coloured badge for the semáforo
    def badge(color):
        colors = {"verde": "green", "amarillo": "yellow", "rojo": "red"}
        bg = colors.get(color, "gray")
        return f"<span class='px-2 py-1 rounded bg-{bg}-200 text-{bg}-800'>{color.title()}</span>"
    df_display = df.copy()
    df_display["semáforo"] = df_display["color"].apply(badge)
    # Hide internal columns that are not needed for the user
    cols_to_show = [c for c in df_display.columns if c not in ["color"]]
    st.dataframe(
        df_display[cols_to_show].style.hide_index().applymap(lambda _: "", subset=["semáforo"]),
        height=400,
    )
    # Render raw HTML badges underneath the dataframe (Streamlit does not support HTML in cells)
    if "semáforo" in df_display.columns:
        for i, row in df_display.iterrows():
            st.markdown(row["semáforo"], unsafe_allow_html=True)

def generate_network(df: pd.DataFrame) -> str:
    """Create a PyVis network graph and return its HTML string.
    Nodes: asegurado, proveedor y siniestro IDs.
    Edges: relationships extracted from the dataframe.
    """
    net = Network(height="600px", width="100%", notebook=False)
    # Add asegurado nodes
    for a in df["id_asegurado"].unique():
        net.add_node(str(a), label=f"Asegurado {a}", shape="dot", color="#1f78b4")
    # Add proveedor nodes (if column exists)
    if "id_proveedor" in df.columns:
        for p in df["id_proveedor"].dropna().unique():
            net.add_node(str(p), label=f"Prov {p}", shape="dot", color="#33a02c")
    # Add siniestro nodes and edges
    for _, row in df.iterrows():
        sin_id = f"S{row['id_siniestro']}"
        net.add_node(sin_id, label=f"Siniestro {row['id_siniestro']}", shape="box", color="#e31a1c")
        net.add_edge(str(row["id_asegurado"]), sin_id)
        if "id_proveedor" in row and pd.notna(row["id_proveedor"]):
            net.add_edge(str(row["id_proveedor"]), sin_id)
    net.toggle_physics(True)
    # Export to HTML string
    html_path = Path(__file__).parent / "network.html"
    net.save_graph(str(html_path))
    with open(html_path, "r", encoding="utf-8") as f:
        return f.read()

def render_network(html: str):
    """Embed the PyVis HTML into Streamlit using components.
    ``st.components.v1.html`` safely renders the interactive graph.
    """
    st.components.v1.html(html, height=600, scrolling=True)

# ---------------------------------------------------------------------
# Streamlit layout
# ---------------------------------------------------------------------

st.set_page_config(page_title="Fraudia Claims Dashboard", layout="wide")

# Inject Tailwind CDN – this runs once per page load.
st.markdown(
    """
    <script src=\"https://cdn.tailwindcss.com\"></script>
    <style>
        body {font-family: 'Inter', sans-serif; background-color: #f9fafb;}
        .stApp {background: transparent;}
    </style>
    """,
    unsafe_allow_html=True,
)

st.title("🚗 Fraudia – Detección de Posibles Fraudes en Siniestros")

# Sidebar navigation (placeholder for future sections)
section = st.sidebar.radio("Navegación", ["Dashboard", "Exploración", "Modelo", "Agente IA"])

if section == "Dashboard":
    df = load_data()
    if not df.empty:
        kpi = compute_kpis(df)
        render_kpis(kpi)
        st.subheader("🗂️ Tabla de Siniestros (Notion‑style)")
        render_table(df)
        st.subheader("🔗 Red de Relaciones")
        network_html = generate_network(df)
        render_network(network_html)
    else:
        st.info("Carga los datos sintéticos para visualizar el dashboard.")
elif section == "Exploración":
    st.info("Sección de notebooks o visualizaciones ad‑hoc será añadida próximamente.")
elif section == "Modelo":
    st.info("Interfaz para entrenar / cargar modelos será implementada en los próximos pasos.")
elif section == "Agente IA":
    st.info("Chat de Gemini RAG que responderá preguntas del analista será integrado aquí.")

# Footer
st.markdown(
    """---\n<div class='text-center text-gray-500'>© 2026 Fraudia‑Claims – Preparado para HackIAthon 2026</div>""",
    unsafe_allow_html=True,
)
